version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: yargs
    versions:
    - "> 12.0.5"
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.20.0
    - 7.22.0
  - dependency-name: mocha
    versions:
    - 8.3.1
