openapi: 3.0.2
info:
  version: v3.2-rc2
  title: Te Rito APIs
  description: >
    **Derived from:** SIF Data Model (New Zealand) v3.2 (rc2)


    **Release Date:** 22-Oct-2020

    # Te Rito Data Domains


    <p>
      <img src="domains/zone512.png" usemap="#DomainMap" />
      <map id="DomainMap" name="DomainMap">
        <area title="Organisation" href="TeRito-OpenAPI-organisation.html#tag/OrganisationOverview" shape="rect" coords="71,65,166,126" />
        <area title="Student &amp; Whānau" href="TeRito-OpenAPI-whanau.html#tag/StudentWhanauOverview" shape="rect" coords="284,331,375,390" />
        <area title="Enrolment" href="TeRito-OpenAPI-enrolment.html#tag/EnrolmentOverview" shape="rect" coords="206,0,301,60" />
        <area title="Hauora / Wellbeing" href="TeRito-OpenAPI-hauora.html#tag/HauoraWellbeingOverview" shape="rect" coords="37,214,132,273" />
        <area title="Aromatawai / Assessment" href="TeRito-OpenAPI-aromatawai.html#tag/AromatawaiAssessmentOverview" shape="rect" coords="378,214,471,272" />
        <area title="Timetable" href="TeRito-OpenAPI-attendance.html#tag/ScheduleAttendanceOverview" shape="rect" coords="132,333,221,391" />
        <area title="Attendance" href="TeRito-OpenAPI-attendance.html#tag/ScheduleAttendanceOverview" shape="rect" coords="344,65,437,126" />
      </map>
    </p>


    Te Rito implements the following SIF Domains:
      - [Organisation & Staff](TeRito-OpenAPI-organisation.html#tag/OrganisationOverview)
      - [Timetable](TeRito-OpenAPI-attendance.html#tag/ScheduleAttendanceOverview)
      - [Student & Whānau](TeRito-OpenAPI-whanau.html#tag/StudentWhanauOverview)
      - [Enrolment](TeRito-OpenAPI-enrolment.html#tag/EnrolmentOverview)
      - [Attendance](TeRito-OpenAPI-attendance.html#tag/ScheduleAttendanceOverview)
      - [Aromatawai/Assessment](TeRito-OpenAPI-aromatawai.html#tag/AromatawaiAssessmentOverview)
      - [Hauora/Wellbeing](TeRito-OpenAPI-hauora.html#tag/HauoraWellbeingOverview)
  contact:
    name: Ministry of Education
    url: http://www.terito.govt.nz
    email: terito@education.govt.nz
  x-logo:
    url: http://www.terito.govt.nz/themes/custom/education_drupal_theme/assets/images/Te_rito_greenflax.svg
    backgroundColor: null
    altText: Te Rito Logo
servers:
  - url: https://southern.edsby.co.nz/sif
    description: The demonstration Te Rito server
  - url: https://nzqa.edsby.co.nz/sif
    description: The NZ Quality Assurance Te Rito server (daily updates)
  - url: https://northern.edsby.co.nz/sif
    description: The Integration Test Te Rito server (end of sprint updates)
security:
  - sifDataObject:
      - DEFERRED
x-tagGroups:
  - name: Organisation
    x-displayName: Organisation Domain
    tags:
      - OrganisationOverview
      - Search
      - Organisation
      - OrganisationRelationship
      - StaffPersonal
      - StaffAssignment
      - StaffTeachingGroupAssignment
      - TeachingGroup
      - AcademicDepartment
      - ProviderCourse
tags:
  - name: OrganisationOverview
    x-displayName: Organisation Overview
    description: >-
      <p> The Organisation domain describes education provider entities (ECEs,
      Schools &amp; Tertiary Education Institutions), Communities (Kāhui Ako,
      Learning Support Clusters, etc.) the relationships between them, and the
      Staff that work at them.</p> <img
      src="domains/SIFNZ-LogicalModel-OrganisationDomain.png"
      usemap="#OrganisationMap" /> <map title="OrganisationMap"
      name="OrganisationMap">
        <area title="Organisation" shape="rect" coords="386,44,602,127" href="#tag/Organisation" />
        <area title="OrganisationRelationship" shape="rect" coords="656,142,789,199" href="#tag/OrganisationRelationship" />
        <area title="StaffPersonal" shape="rect" coords="466,472,555,536" href="#tag/StaffPersonal" />
        <area title="StaffAssignment" shape="rect" coords="664,212,754,284" href="#tag/StaffAssignment" />
        <area title="StaffTeachingGroupAssignment" shape="rect" coords="38,263,215,303" href="#tag/StaffTeachingGroupAssignment" />
        <area title="ProviderCourse" shape="rect" coords="387,284,476,320" href="#tag/ProviderCourse" />
        <area title="TeachingGroup" shape="rect" coords="215,65,305,107" href="#tag/TeachingGroup" />
        <area title="AcademicDepartment" shape="rect" coords="196,392,316,427" href="#tag/AcademicDepartment" />
      </map>  
  - name: Search
    x-displayName: Search
    description: Search operation returning partial <a
      href="#tag/StaffPersonal">StaffPersonal</a> and <a
      href="#tag/StudentPersonal">StudentPersonal</a> objects.
  - name: Organisation
    x-displayName: Organisation
    description: Operations on recognised Education Provider entities (ECEs, Schools &
      Tertiary  Education Institutions), Communities (Kāhui Ako, Learning
      Support Clusters, etc.), and  others (Teen Parent Units, Activity Centres.
      etc.)
  - name: OrganisationRelationship
    x-displayName: Organisation Relationship
    description: <p>Operations on recognised relationships between two education
      Organisations. The two organisations are referred to as the Source
      Organisation and the Related Organisation.</p> <p>RelationshipType records
      the nature of the relationship between the two organisations, and gives
      guidance on which is the Source Organisation and which is the Related
      Organisation.</p>
  - name: StaffPersonal
    x-displayName: Staff Personal
    description: >-
      <p>Operations on the personal contact and demographic information relating
      to

      staff members, who might be a teacher or other employee of a Provider.</p>


      <p>Searching for staff personal record by name, email address (or whatever) is

      available via <a href="#tag/Search">Te Rito Search API</a>.</p>


      <p>Non personal information relating to the staff member's relationship with Providers

      is stored in the <a href="#tag/StaffAssignment">StaffAssignment</a> data object.</p>
  - name: StaffAssignment
    x-displayName: Staff Assignment
    description: >-
      <p>Operations on the assignment of a Staff member to their role at a
      Providers or other 

      Organisation. A staff member may have only have a single role at each Provider or Kāhui Ako at any one time 

      (via the Organisation data object)</p>

      <p>Role assignments can be restricted to categories of Students with the StaffSubjectList and
       YearLevelList. This allows for assignment to roles with particular responsibility for general 
       cohorts of students, such as "Head of Department (Maths)" or "Year 8 Student Dean".</p> 
       <p>While assignment to student contact roles such as Subject Teacher, Homeroom Teacher, 
       Whānau Teacher or House Master is made with this data object; Details of the particular group 
       of specific students the staff member is responsible for are made via the 
       <a href="#tag/TeachingGroup">TeachingGroup</a> data object.</p>
  - name: StaffTeachingGroupAssignment
    x-displayName: Staff Teaching Group Assignment
    description: <p>Operations on the assignment of a Staff member to a particular role
      with a particular TeachingGroup at a Provider</p>
  - name: TeachingGroup
    x-displayName: Teaching Group
    description: <p>Operations on teaching Classes of students. Such classes can have
      multiple staff  assigned in a variety of roles (via <a
      href="#tag/StaffTeachingGroupAssignment">StaffTeachingGroupAssignment</a>),  may
      be assigned students from multiple year levels (via <a
      href="#tag/StudentTeachingGroupEnrolment">StudentTeachingGroupEnrolment</a>),
      and may be taught multiple <a
      href="#tag/ProviderCourse">ProviderCourses</a>.</p>
  - name: AcademicDepartment
    x-displayName: Academic Department
    description: <p>Operations on academic departments within a provider, each of which
      groups <a href="#tagProviderCourse">ProviderCourses</a> and  <a
      href="#tagTeachingGroup">TeachingGroups</a> according to SubjectArea.</p>
  - name: ProviderCourse
    x-displayName: Provider Course
    description: <p>Operations on provider defined Courses that Students enrol in,  and may
      be assessed for, and achieve passes in.</p>
paths:
  /search:
    get:
      tags:
        - Search
      summary: Search for Staff and Students
      description: >-
        Search operation returning partial <a
        href="#tag/StaffPersonal">StaffPersonal</a>

        and <a href="#tag/StudentPersonal">StudentPersonal</a> objects.
      operationId: search
      security:
        - sifDataObject:
            - FIRST
            - SUPS
            - SMS
  /organisation:
    post:
      tags:
        - Organisation
        - OrganisationBulk
      summary: Create one or more Organisations
      description: Bulk operation to create one or more Organisations, each of which
        represents a single recognised Education Provider entity (ECEs, Schools
        & Tertiary Education Institutions), Community (Kāhui Ako, Learning
        Support Clusters, etc.), or others unit(Teen Parent Units, Activity
        Centres. etc.)
      operationId: createOrganisations
      security:
        - sifDataObject:
            - FIRST
    get:
      tags:
        - Organisation
        - OrganisationBulk
      summary: Retrieve one or more Organisations
      description: Bulk operation to retrieve all available Organisations, each of which
        represents a single recognised Education Provider entity (ECEs, Schools
        & Tertiary  Education Institutions), Community (Kāhui Ako, Learning
        Support Clusters, etc.), or others unit(Teen Parent Units, Activity
        Centres. etc.)
      operationId: getOrganisations
      security:
        - sifDataObject:
            - SMS
            - FIRST
            - SUPS
    put:
      tags:
        - Organisation
        - OrganisationBulk
      summary: Update one or more Organisations
      description: "Bulk operation to update one or more Organisations, each of which
        represents a single recognised Education Provider entity (ECEs, Schools
        & Tertiary  Education Institutions), Community (Kāhui Ako, Learning
        Support Clusters, etc.), or others unit(Teen Parent Units, Activity
        Centres. etc.)    "
      operationId: updateOrganisations
      security:
        - sifDataObject:
            - FIRST
    patch:
      tags:
        - Organisation
        - OrganisationBulk
      summary: Patch one or more Organisations
      description: Bulk operation to update one or more fields of one or more
        Organisations, each of which represents a single recognised Education
        Provider entity (ECEs, Schools & Tertiary  Education Institutions),
        Community (Kāhui Ako, Learning Support Clusters, etc.), or others
        unit(Teen Parent Units, Activity Centres. etc.)
      operationId: patchOrganisations
      security:
        - sifDataObject:
            - FIRST
  "/organisation/{OrganisationRefId}":
    get:
      tags:
        - Organisation
        - OrganisationSingle
      summary: Retrieve a single Organisation
      description: "Retrive a particular Organisation, which represents a single recognised
        Education Provider entity (ECEs, Schools & Tertiary  Education
        Institutions), Community (Kāhui Ako, Learning Support Clusters, etc.),
        or others unit(Teen Parent Units, Activity Centres. etc.)    "
      operationId: getOrganisation
      security:
        - sifDataObject:
            - SMS
            - FIRST
            - SUPS
    put:
      tags:
        - Organisation
        - OrganisationSingle
      summary: Update a single Organisation
      description: "Update a particular Organisation, which represents a single recognised
        Education Provider entity (ECEs, Schools & Tertiary  Education
        Institutions), Community (Kāhui Ako, Learning Support Clusters, etc.),
        or others unit(Teen Parent Units, Activity Centres. etc.)    "
      operationId: updateOrganisation
      security:
        - sifDataObject:
            - FIRST
    patch:
      tags:
        - Organisation
        - OrganisationSingle
      summary: Patch a single Organisation
      description: Update one or more fields of a particular Organisation, which represents
        a single recognised Education Provider entity (ECEs, Schools &
        Tertiary  Education Institutions), Community (Kāhui Ako, Learning
        Support Clusters, etc.), or others unit(Teen Parent Units, Activity
        Centres. etc.)
      operationId: patchOrganisation
      security:
        - sifDataObject:
            - FIRST
  "/organisation/{OrganisationRefId}/organisationrelationship":
    post:
      tags:
        - OrganisationRelationship
        - OrganisationRelationshipBulk
      summary: Create one or more OrganisationRelationships
      description: Bulk operation to create one or more OrganisationRelationships, each of
        which represents  a single recognised relationship between two education
        Organisations. The two organisations are referred to as the Source
        Organisation and the Related Organisation.</p> <p>RelationshipType
        records the nature of the relationship between the two
        organisations,  and gives guidance on which is the Source Organisation
        and which is the Related Organisation.</p>
      operationId: createOrganisationRelationships
      security:
        - sifDataObject:
            - FIRST
    get:
      tags:
        - OrganisationRelationship
        - OrganisationRelationshipBulk
      summary: Get a list of OrganisationRelationships
      description: Bulk operation to retrieve all available OrganisationRelationships where
        the given OrganisationRelationshipRefId represents either the
        <strong>Source</strong> or <strong>Related</strong> organisation in the
        OrganisationRelationship.</p> <p> Each OrganisationRelationship
        represents a single recognised relationship between two education
        Organisations. The two organisations are referred to as the
        Source  Organisation and the Related Organisation.</p>
        <p>RelationshipType records the nature of the relationship between the
        two organisations,  and gives guidance on which is the Source
        Organisation and which is the Related Organisation.</p>
      operationId: getOrganisationRelationships
      security:
        - sifDataObject:
            - SMS
            - FIRST
            - SUPS
    put:
      tags:
        - OrganisationRelationship
        - OrganisationRelationshipBulk
      summary: Update a list of OrganisationRelationships
      description: >-
        Bulk operation to update a set of OrganisationRelationships, each of
        which represents a  single recognised relationship between two education
        Organisations. The two organisations
         are referred to as the Source Organisation and the Related Organisation.</p>
        <p>RelationshipType records the nature of the relationship between the two organisations,  and gives guidance on which is the Source Organisation and which is the Related Organisation.</p>
      operationId: updateOrganisationRelationships
      security:
        - sifDataObject:
            - FIRST
    patch:
      tags:
        - OrganisationRelationship
        - OrganisationRelationshipBulk
      summary: Patch a list of OrganisationRelationships
      description: Bulk operation to update one or more fields of a set of
        OrganisationRelationships, each of which represents a  single recognised
        relationship between two education Organisations. The two organisations
        are referred to as the Source Organisation and the Related
        Organisation.</p> <p>RelationshipType records the nature of the
        relationship between the two organisations,  and gives guidance on which
        is the Source Organisation and which is the Related Organisation.</p>
      operationId: patchOrganisationRelationships
      security:
        - sifDataObject:
            - FIRST
  "/organisation/{OrganisationRefId}/organisationrelationship/{OrganisationRelationshipRefId}":
    get:
      tags:
        - OrganisationRelationship
        - OrganisationRelationshipSingle
      summary: Get a single OperationRelationship
      description: Retrieve a particular OrganisationRelationship, which represents
        a  single recognised relationship between two education Organisations.
        The two organisations are referred to  as the Source Organisation and
        the Related Organisation.</p> <p>RelationshipType records the nature of
        the relationship between the two organisations,  and gives guidance on
        which is the Source Organisation and which is the Related
        Organisation.</p>
      operationId: getOrganisationRelationship
      security:
        - sifDataObject:
            - SMS
            - FIRST
            - SUPS
    put:
      tags:
        - OrganisationRelationship
        - OrganisationRelationshipSingle
      summary: Update a single OperationRelationship
      description: Update a particular OrganisationRelationship, which represents a  single
        recognised relationship between two education Organisations. The two
        organisations are referred to  as the Source Organisation and the
        Related Organisation.</p> <p>RelationshipType records the nature of the
        relationship between the two organisations,  and gives guidance on which
        is the Source Organisation and which is the Related Organisation.</p>
      security:
        - sifDataObject:
            - FIRST
    patch:
      tags:
        - OrganisationRelationship
        - OrganisationRelationshipSingle
      summary: Patch a single OperationRelationship
      description: Update one or more fields of a particular OrganisationRelationship,
        which represents a  single recognised relationship between two education
        Organisations. The two organisations are referred to as the Source
        Organisation and the Related Organisation.</p> <p>RelationshipType
        records the nature of the relationship between the two
        organisations,  and gives guidance on which is the Source Organisation
        and which is the Related Organisation.</p>
      operationId: patchOrganisationRelationship
      security:
        - sifDataObject:
            - FIRST
  /staffpersonal:
    post:
      tags:
        - StaffPersonal
        - StaffPersonalBulk
      summary: Create one or more StaffPersonals
      description: <p>Bulk operation to create one or more StaffPersonal records of the
        personal contact and demographic information relating to a single staff
        member, who might be a teacher or other employee of the given
        Provider.</p>
      operationId: createStaffPersonals
      security:
        - sifDataObject:
            - SUPS
            - SMS
    get:
      tags:
        - StaffPersonal
        - StaffPersonalBulk
      summary: Retrieve one or more StaffPersonals
      description: <p>Bulk operation to retrieve all available StaffPersonal records of the
        personal contact and demographic information relating to a single staff
        member, who might be a teacher or other  employee of the given
        Provider.</p>
      operationId: getStaffPersonals
      security:
        - sifDataObject:
            - SUPS
            - SMS
    put:
      tags:
        - StaffPersonal
        - StaffPersonalBulk
      summary: Update one or more StaffPersonals
      description: <p>Bulk operation to update one or more StaffPeraonal records of the
        personal contact and  demographic information relating to a single staff
        member, who might be a teacher or other employee of the given
        Provider.</p>
      operationId: updateStaffPersonals
      security:
        - sifDataObject:
            - SUPS
            - SMS
    patch:
      tags:
        - StaffPersonal
        - StaffPersonalBulk
      summary: Patch one or more StaffPersonals
      description: <p>Bulk operation to update one or more fields of one or more
        StaffPersonal records of the personal contact and demographic
        information relating to a single staff member, who might be a teacher or
        other employee of the given Provider.</p>
      operationId: patchStaffPersonals
      security:
        - sifDataObject:
            - SUPS
            - SMS
  "/staffpersonal/{StaffPersonalRefId}":
    get:
      tags:
        - StaffPersonal
        - StaffPersonalSingle
      summary: Retrieve a single StaffPersonal
      description: Retrieve a single record of the personal contact and demographic
        information relating to a single staff member, who might be a teacher or
        other employee of the given Provider.</p>
      operationId: getStaffPersonal
      security:
        - sifDataObject:
            - SUPS
            - SMS
    put:
      tags:
        - StaffPersonal
        - StaffPersonalSingle
      summary: Update a single StaffPersonal
      description: Update a single record of the personal contact and demographic
        information relating to a single staff member, who might be a teacher or
        other employee of the given Provider.</p>
      security:
        - sifDataObject:
            - SUPS
            - SMS
      operationId: updateStaffPersonal
    patch:
      tags:
        - StaffPersonal
        - StaffPersonalSingle
      summary: Patch a single StaffPersonal
      description: Update one or more fields of asingle record of the personal contact and
        demographic information relating to a single staff member, who might be
        a teacher or other employee of the given Provider.</p>
      operationId: patchStaffPersonal
      security:
        - sifDataObject:
            - SUPS
            - SMS
  /staffassignment:
    post:
      tags:
        - StaffAssignment
        - StaffAssignmentBulk
      summary: Create one or more StaffAssignments
      description: <p>Bulk operation to create one or more assignments of a Staff member to
        their role at a Providers or other  Organisation.</p> <p>A staff member
        may have only have a single role at each Provider or Kāhui Ako at any
        one time (via the Organisation data object)</p>
      operationId: createStaffAssignments
      security:
        - sifDataObject:
            - SMS
            - SUPS
    get:
      tags:
        - StaffAssignment
        - StaffAssignmentBulk
      summary: Retrieve one or more StaffAssignments
      description: "<p>Bulk operation to retrieve all available assignments of a Staff
        member to their role at the given Provider or other Organisation.</p>
        <p>A staff member may have only have a single role at each Provider or
        Kāhui Ako at any one time (via the Organisation data object)</p>    "
      operationId: getStaffAssignments
      security:
        - sifDataObject:
            - SMS
            - SUPS
    put:
      tags:
        - StaffAssignment
        - StaffAssignmentBulk
      summary: Update one or more StaffAssignments
      description: "<p>Bulk operation to update one or more assignments of a Staff member
        to their role at the given Provider or other Organisation.</p> <p>A
        staff member may have only have a single role at each Provider or Kāhui
        Ako at any one time (via the Organisation data object)</p>    "
      operationId: updateStaffAssignments
      security:
        - sifDataObject:
            - SMS
            - SUPS
    patch:
      tags:
        - StaffAssignment
        - StaffAssignmentBulk
      summary: Patch one or more StaffAssignments
      description: "<p>Bulk operation to update one or more fields of one or more
        assignments of a Staff member to their role at the given Provider or
        other Organisation.</p> <p>A staff member may have only have a single
        role at each Provider or Kāhui Ako at any one time (via the Organisation
        data object)</p>    "
      operationId: patchStaffAssignments
      security:
        - sifDataObject:
            - SMS
            - SUPS
  "/staffassignment/{StaffPersonalRefId}":
    get:
      tags:
        - StaffAssignment
        - StaffAssignmentSingle
      summary: Retrieve a single StaffAssignment
      description: "<p>Retrieve a single assignment of a Staff member to their role at the
        given Provider or other Organisation.</p> <p>A staff member may have
        only have a single role at each Provider or Kāhui Ako at any one time
        (via the Organisation data object)</p>    "
      operationId: getStaffAssignment
      security:
        - sifDataObject:
            - SMS
            - SUPS
    put:
      tags:
        - StaffAssignment
        - StaffAssignmentSingle
      summary: Update a single StaffAssignment
      description: "<p>Update a single assignment of a Staff member to their role at the
        given Provider or other Organisation.</p> <p>A staff member may have
        only have a single role at each Provider or Kāhui Ako at any one time
        (via the Organisation data object)</p>    "
      operationId: updateStaffAssignment
      security:
        - sifDataObject:
            - SMS
            - SUPS
    patch:
      tags:
        - StaffAssignment
        - StaffAssignmentSingle
      summary: Patch a single StaffAssignment
      description: "<p>Update one or more fields of a single assignment of a Staff member
        to their role at the given Provider or other Organisation.</p> <p>A
        staff member may have only have a single role at each Provider or Kāhui
        Ako at any one time (via the Organisation data object)</p>    "
      operationId: patchStaffAssignment
      security:
        - sifDataObject:
            - SMS
            - SUPS
  "/staffpersonal/{StaffPersonalRefId}/staffassignment":
    get:
      tags:
        - StaffAssignment
        - StaffAssignmentByStaff
      summary: Retrieve StaffAssignments by Staff Member
      description: "<p>Retrieve all available assignments of a particular Staff member to
        their role at any Provider or other Organisation.</p> <p>A staff member
        may have only have a single role at each Provider or Kāhui Ako at any
        one time (via the Organisation data object)</p>    "
      operationId: getStaffAssignmentsByStaff
      security:
        - sifDataObject:
            - SMS
            - SUPS
  /staffteachinggroupassignment:
    post:
      tags:
        - StaffTeachingGroupAssignment
        - StaffTeachingGroupAssignmentBulk
      summary: Create one or more StaffTeachingGroupAssignments
      description: <p>Bulk operation to create one or more assignments of Staff members to
        particular roles with a particular TeachingGroup at the given
        Provider</p>
      operationId: createStaffTeachingGroupAssignments
      security:
        - sifDataObject:
            - SMS
    get:
      tags:
        - StaffTeachingGroupAssignment
        - StaffTeachingGroupAssignmentBulk
      summary: Retreive one or more StaffTeachingGroupAssignments
      description: <p>Bulk operation to retrieve all available assignments of Staff members
        to particular roles with a particular TeachingGroup at the given
        Provider</p>
      operationId: getStaffTeachingGroupAssignments
      security:
        - sifDataObject:
            - SMS
    put:
      tags:
        - StaffTeachingGroupAssignment
        - StaffTeachingGroupAssignmentBulk
      summary: Update one or more StaffTeachingGroupAssignments
      description: <p>Bulk operation to update one or more assignments of Staff members to
        particular roles with a particular TeachingGroup at the given
        Provider</p>
      operationId: updateStaffTeachingGroupAssignments
      security:
        - sifDataObject:
            - SMS
    patch:
      tags:
        - StaffTeachingGroupAssignment
        - StaffTeachingGroupAssignmentBulk
      summary: Patch one or more StaffTeachingGroupAssignments
      description: <p>Bulk operation to update one or more fields of one or more
        assignments of Staff members to particular roles with a particular
        TeachingGroup at the given Provider</p>
      operationId: patchStaffTeachingGroupAssignments
      security:
        - sifDataObject:
            - SMS
  "/staffteachinggroupassignment/{StaffTeachingGroupAssignmentRefId}":
    get:
      tags:
        - StaffTeachingGroupAssignment
        - StaffTeachingGroupAssignmentSingle
      summary: Retrieve a single StaffTeachingGroupAssignment
      description: <p>Retrieve a particular assignment of a Staff member to a particular
        role with a particular TeachingGroup at the given Provider</p>
      operationId: getStaffTeachingGroupAssignment
      security:
        - sifDataObject:
            - SMS
    put:
      tags:
        - StaffTeachingGroupAssignment
        - StaffTeachingGroupAssignmentSingle
      summary: Update a single StaffTeachingGroupAssignment
      description: <p>Update a particular assignment of a Staff member to a particular role
        with a particular TeachingGroup at the given Provider</p>
      operationId: updateStaffTeachingGroupAssignment
      security:
        - sifDataObject:
            - SMS
    patch:
      tags:
        - StaffTeachingGroupAssignment
        - StaffTeachingGroupAssignmentSingle
      summary: Patch a single StaffTeachingGroupAssignment
      description: <p>Update one or more fields of a particular assignment of a Staff
        member to a particular role with a particular TeachingGroup at the given
        Provider</p>
      operationId: patchStaffTeachingGroupAssignment
      security:
        - sifDataObject:
            - SMS
  "/staffpersonal/{StaffPersonalRefId}/staffteachinggroupassignment":
    get:
      tags:
        - StaffTeachingGroupAssignment
        - StaffTeachingGroupAssignmentSearch
      summary: Retrieve StaffTeachingGroupAssignments by Staff member
      description: <p>Retrieve all available assignments of a particular Staff member to
        any role with any TeachingGroup at the given Provider</p>
      operationId: getStaffTeachingGroupAssignmentByStaff
      security:
        - sifDataObject:
            - SMS
  "/teachinggroup/{TeachingGroupRefId}/staffteachinggroupassignment":
    get:
      tags:
        - StaffTeachingGroupAssignment
        - StaffTeachingGroupAssignmentSearch
      summary: Retrieve StaffTeachingGroupAssignments by TeachingGroup
      description: <p>Retrieve all available assignments of any staff members to  a
        particulr TeachingGroup at the given Provider</p>
      operationId: getStaffTeachingGroupAssignmentByTeachingGroup
      security:
        - sifDataObject:
            - SMS
  /teachinggroup:
    post:
      tags:
        - TeachingGroup
        - TeachingGroupBulk
      summary: Create one or more TeachingGroups
      description: <p>Bulk operation to create one or more TeachingGroups which can have
        multiple staff  assigned in a variety of roles (via <a
        href="#tag/StaffTeachingGroupAssignment">StaffTeachingGroupAssignment</a>),  may
        be assigned students from multiple year levels (via <a
        href="#tag/StudentTeachingGroupEnrolment">StudentTeachingGroupEnrolment</a>),
        and may be taught multiple <a
        href="#tag/ProviderCourse">ProviderCourses</a>.</p>
      operationId: createTeachingGroups
      security:
        - sifDataObject:
            - SMS
    get:
      tags:
        - TeachingGroup
        - TeachingGroupBulk
      summary: Create one or more TeachingGroups
      description: <p>Bulk operation to retrieve all available TeachingGroups from the
        given Provider.  TeachingGroups can have multiple staff  assigned in a
        variety of roles (via <a
        href="#tag/StaffTeachingGroupAssignment">StaffTeachingGroupAssignment</a>),  may
        be assigned students from multiple year levels (via <a
        href="#tag/StudentTeachingGroupEnrolment">StudentTeachingGroupEnrolment</a>),
        and may be taught multiple <a
        href="#tag/ProviderCourse">ProviderCourses</a>.</p>
      operationId: getTeachingGroups
      security:
        - sifDataObject:
            - SMS
    put:
      tags:
        - TeachingGroup
        - TeachingGroupBulk
      summary: Create one or more TeachingGroups
      description: <p>Bulk operation to update one or more TeachingGroups, which can have
        multiple staff  assigned in a variety of roles (via <a
        href="#tag/StaffTeachingGroupAssignment">StaffTeachingGroupAssignment</a>),  may
        be assigned students from multiple year levels (via <a
        href="#tag/StudentTeachingGroupEnrolment">StudentTeachingGroupEnrolment</a>),
        and may be taught multiple <a
        href="#tag/ProviderCourse">ProviderCourses</a>.</p>
      operationId: updateTeachingGroups
      security:
        - sifDataObject:
            - SMS
    patch:
      tags:
        - TeachingGroup
        - TeachingGroupBulk
      summary: Patch one or more TeachingGroups
      description: <p>Bulk operation to update one or more fields of one or more
        TeachingGroups, which can have multiple staff  assigned in a variety of
        roles (via <a
        href="#tag/StaffTeachingGroupAssignment">StaffTeachingGroupAssignment</a>),  may
        be assigned students from multiple year levels (via <a
        href="#tag/StudentTeachingGroupEnrolment">StudentTeachingGroupEnrolment</a>),
        and may be taught multiple <a
        href="#tag/ProviderCourse">ProviderCourses</a>.</p>
      operationId: patchTeachingGroups
      security:
        - sifDataObject:
            - SMS
  "/teachinggroup/{TeachingGroupRefId}":
    get:
      tags:
        - TeachingGroup
        - TeachingGroupSingle
      summary: Retrieve a single TeachingGroup
      description: <p>Retrieve a particular TeachingGroup, which can have multiple staff
        assigned in a variety of roles (via <a
        href="#tag/StaffTeachingGroupAssignment">StaffTeachingGroupAssignment</a>),  may
        be assigned students from multiple year levels (via <a
        href="#tag/StudentTeachingGroupEnrolment">StudentTeachingGroupEnrolment</a>),
        and may be taught multiple <a
        href="#tag/ProviderCourse">ProviderCourses</a>.</p>
      operationId: getTeachingGroup
      security:
        - sifDataObject:
            - SMS
    put:
      tags:
        - TeachingGroup
        - TeachingGroupSingle
      summary: Update a single TeachingGroup
      description: <p>Update a particular TeachingGroup, which can have multiple staff
        assigned in a variety of roles (via <a
        href="#tag/StaffTeachingGroupAssignment">StaffTeachingGroupAssignment</a>),  may
        be assigned students from multiple year levels (via <a
        href="#tag/StudentTeachingGroupEnrolment">StudentTeachingGroupEnrolment</a>),
        and may be taught multiple <a
        href="#tag/ProviderCourse">ProviderCourses</a>.</p>
      operationId: updateTeachingGroup
      security:
        - sifDataObject:
            - SMS
    patch:
      tags:
        - TeachingGroup
        - TeachingGroupSingle
      summary: Patch a single TeachingGroup
      description: <p>Update one or more fields of a particular TeachingGroup, which can
        have multiple staff assigned in a variety of roles (via <a
        href="#tag/StaffTeachingGroupAssignment">StaffTeachingGroupAssignment</a>),  may
        be assigned students from multiple year levels (via <a
        href="#tag/StudentTeachingGroupEnrolment">StudentTeachingGroupEnrolment</a>),
        and may be taught multiple <a
        href="#tag/ProviderCourse">ProviderCourses</a>.</p>
      operationId: patchTeachingGroup
      security:
        - sifDataObject:
            - SMS
  "/staffpersonal/{StaffPersonalRefId}/teachinggroup":
    get:
      tags:
        - TeachingGroup
        - TeachingGroupSearch
      summary: Retrieve TeachingGroups by Staff member
      description: <p>Retrieve all available TeachingGroup where the given staff member has
        been assigned a role (via <a
        href="#tag/StaffTeachingGroupAssignment">StaffTeachingGroupAssignment</a>)</p>
      operationId: getTeachingGroupsByStaff
      security:
        - sifDataObject:
            - SMS
  "/studentpersonal/{StudentPersonalRefId}/teachinggroup":
    get:
      tags:
        - TeachingGroup
        - TeachingGroupSearch
      summary: Retrieve TeachingGroups by Student
      description: <p>Retrieve all available TeachingGroup where the given Student has been
        enrolled  (via <a
        href="#tag/StudentTeachingGroupEnrolment">StudentTeachingGroupEnrolment</a>)</p>
      operationId: getTeachingGroupsByStudent
      security:
        - sifDataObject:
            - SMS
  /academicdepartment:
    post:
      tags:
        - AcademicDepartment
        - AcademicDepartmentBulk
      summary: Create one or more AcademicDepartments
      description: Bulk operation to create one or more AcademicDepartments which group <a
        href="#tagProviderCourse">ProviderCourses</a> and  <a
        href="#tagTeachingGroup">TeachingGroups</a> according to
        SubjectArea.</p>
      operationId: createAcademicDepartments
    get:
      tags:
        - AcademicDepartment
        - AcademicDepartmentBulk
      summary: Retrieve all AcademicDepartments
      description: Bulk operation to retrieve all available AcademicDepartments, within the
        scope of the given Provider.  Each AcademicDepartment groups <a
        href="#tagProviderCourse">ProviderCourses</a> and  <a
        href="#tagTeachingGroup">TeachingGroups</a> according to
        SubjectArea.</p>
      operationId: getAcademicDepartments
    put:
      tags:
        - AcademicDepartment
        - AcademicDepartmentBulk
      summary: Update one or more AcademicDepartments
      description: Bulk operation to update all available AcademicDepartments, within the
        scope of the given Provider.  Each AcademicDepartment groups <a
        href="#tagProviderCourse">ProviderCourses</a> and  <a
        href="#tagTeachingGroup">TeachingGroups</a> according to
        SubjectArea.</p>
      operationId: updateAcademicDepartments
    patch:
      tags:
        - AcademicDepartment
        - AcademicDepartmentBulk
      summary: Patch one or more AcademicDepartments
      description: Bulk operation to update one or more fields of one or more
        AcademicDepartments, within the scope of the given Provider.  Each
        AcademicDepartment groups <a
        href="#tagProviderCourse">ProviderCourses</a> and  <a
        href="#tagTeachingGroup">TeachingGroups</a> according to
        SubjectArea.</p>
      operationId: patchAcademicDepartments
  "/academicdepartment/{AcademicDepartmentRefId}":
    get:
      tags:
        - AcademicDepartment
        - AcademicDepartmentSingle
      summary: Retrieve a single AcademicDepartment
      description: Retrieve a particular AcademicDepartment which groups <a
        href="#tagProviderCourse">ProviderCourses</a> and  <a
        href="#tagTeachingGroup">TeachingGroups</a> according to
        SubjectArea.</p>
      operationId: getAcademicDepartment
    put:
      tags:
        - AcademicDepartment
        - AcademicDepartmentSingle
      summary: Update a single AcademicDepartment
      description: Update a particular AcademicDepartment which groups <a
        href="#tagProviderCourse">ProviderCourses</a> and  <a
        href="#tagTeachingGroup">TeachingGroups</a> according to
        SubjectArea.</p>
      operationId: updateAcademicDepartment
    patch:
      tags:
        - AcademicDepartment
        - AcademicDepartmentSingle
      summary: Patch a single AcademicDepartment
      description: Update one or more fields of a particular AcademicDepartment which
        groups <a href="#tagProviderCourse">ProviderCourses</a> and  <a
        href="#tagTeachingGroup">TeachingGroups</a> according to
        SubjectArea.</p>
      operationId: patchAcademicDepartment
  /providercourse:
    post:
      tags:
        - ProviderCourse
        - ProviderCourseBulk
      summary: Create one or more ProviderCourses
      description: <p>Bulk operation to create one or more provider defined Courses that
        Students enrol in,  may be assessed for, and achieve passes in.</p>
      operationId: createProviderCourses
    get:
      tags:
        - ProviderCourse
        - ProviderCourseBulk
      summary: Retrieve one or more ProviderCourses
      description: "<p>Bulk operation to retrieve one or more provider defined Courses that
        Students enrol in,  may be assessed for, and achieve passes in.</p>    "
      operationId: getProviderCourses
    put:
      tags:
        - ProviderCourse
        - ProviderCourseBulk
      summary: Update one or more ProviderCourses
      description: "<p>Bulk operation to update one or more provider defined Courses that
        Students enrol in,  may be assessed for, and achieve passes in.</p>    "
      operationId: updateProviderCourses
    patch:
      tags:
        - ProviderCourse
        - ProviderCourseBulk
      summary: Patch one or more ProviderCourses
      description: <p>Bulk operation to update one or more fields of one or more provider
        defined Courses that Students enrol in, may be assessed for, and achieve
        passes in.</p>
      operationId: patchProviderCourses
  "/providercourse/{ProviderCourseRefId}":
    get:
      tags:
        - ProviderCourse
        - ProviderCourseSingle
      summary: Retrieve a single ProviderCourse
      description: "<p>Retrieve a particular provider defined Course that Students enrol
        in,  may be assessed for, and achieve passes in.</p>    "
      operationId: getProviderCourse
    put:
      tags:
        - ProviderCourse
        - ProviderCourseSingle
      summary: Update a single ProviderCourse
      description: <p>Update one or more fields of a particular provider defined Course
        that Students enrol in,  may be assessed for, and achieve passes in.</p>
      operationId: updateProviderCourse
    patch:
      tags:
        - ProviderCourse
        - ProviderCourseSingle
      summary: Patch a single ProviderCourse
      description: <p>Update one or more fields of a particular provider defined Course
        that Students enrol in,  may be assessed for, and achieve passes in.</p>
      operationId: patchProviderCourse
components:
  securitySchemes:
    sifDataObject:
      type: oauth2
      description: OAuth 2.0 authentication is applied to all SIF data objects. Scope
        provided in the  JWT access token will be verified against Te Rito user
        account role, that is separately provisioned.
      flows:
        clientCredentials:
          tokenUrl: https://login.microsoftonline.com/6418b52e-37db-4261-bcf7-d64c4b0a59f5/oauth2/v2.0/token
          scopes:
            FIRST: 'Authorised as FIRST integration hub, able to maintain <a
              href="#tag/Organisation">Organisation</a> and  <a
              href="#tag/OrganisationRelationship">OrganisationRelationship</a>.
              SIF role # <code>2501</code>'
            SUPS: 'Authorised as Secondary User Provisioning System (SUPS)
              integration hub, able to maintain <a
              href="#tag/StaffPersonal">StaffPersonal</a> and  <a
              href="#tag/StaffAssignment">StaffAssignment</a>. SIF role #
              <code>2502</code>'
            NZQA: 'Authorised client able to maintain <a
              href="#tag/LearningStandard">LearningStandard</a> and  <a
              href="#tag/Credential">Credential</a>. SIF role #
              <code>2503</code>'
            LSR: 'Authorised client able to maintain <a
              href="#tag/StudentLearningSupport">StudentLearningSupport</a>, <a
              href="#tag/StudentLearningSupportResponse">StudentLearningSupportResponse</a>
              and Learning Support need flavours of <a
              href="#tag/WellbeingCharacteristic">WellbeingCharacteristic</a>.
              SIF role # <code>2504</code>'
            SMS: "Authorised as SMS Client on behalf of a particular provider
              (School/ECE). SIF role # <code>2505</code>"
            DEFERRED: Authorised to access the deferred APIs
